export const events = [
  {
    slug: "ar-rahman-live-san-francisco-2026",
    image: "/images/event1.jpeg",
    title: "A.R. Rahman Live Symphonic Magic",
    location: "Davies Symphony Hall, San Francisco, CA",
    date: "July 2, 2026",
    time: "7:30 PM - 10:30 PM",
  },
  {
    slug: "yuvan-shankar-raja-rhythm-puducherry",
    image: "/images/event4.jpeg",
    title: "High On U1: Yuvan Shankar Raja Live",
    location: "Expo Ground, Puducherry, India",
    date: "July 4, 2026",
    time: "6:00 PM - 11:00 PM",
  },
  {
    slug: "eminem-the-momp-tour-detroit",
    image: "/images/event3.jpeg",
    title: "Eminem: The Music To Be Murdered By Live",
    location: "Ford Field, Detroit, MI",
    date: "August 12, 2026",
    time: "8:00 PM - 11:30 PM",
  },
  {
    slug: "coldplay-music-spheres-london",
    image: "/images/event5.jpeg",
    title: "Coldplay: Music of the Spheres World Tour",
    location: "Wembley Stadium, London, UK",
    date: "August 15, 2026",
    time: "5:30 PM - 11:00 PM",
  },
  {
    slug: "anirudh-xv-tour-trenton-2026",
    image: "/images/event2.jpeg",
    title: "Rockstar Anirudh XV Arena Tour",
    location: "CURE Insurance Arena, Trenton, NJ",
    date: "August 30, 2026",
    time: "6:00 PM - 9:30 PM",
  },
  {
    slug: "nsync-popodyssey-reunion-la",
    image: "/images/event1.jpeg",
    title: "*NSYNC: The Ultimate Reunion Tour",
    location: "Crypto.com Arena, Los Angeles, CA",
    date: "September 18, 2026",
    time: "7:30 PM - 11:00 PM",
  },
  {
    slug: "harris-jayaraj-classic-chennai",
    image: "/images/event5.jpeg",
    title: "Harris Jayaraj: Musical Arena Experience",
    location: "Nehru Indoor Stadium, Chennai, TN",
    date: "October 10, 2026",
    time: "6:30 PM - 10:30 PM",
  },
  {
    slug: "pradeep-kumar-maruvarthai-trichy",
    image: "/images/event3.jpeg",
    title: "Pradeep Kumar: Musical Intimacy Live",
    location: "Anna Stadium Open Arena, Trichy, TN",
    date: "October 24, 2026",
    time: "7:00 PM - 10:00 PM",
  },
  {
    slug: "fatima-hadid-soul-rabat",
    image: "/images/event4.jpeg",
    title: "Fatima Hadid: Acoustic Soul Sessions",
    location: "Théâtre National Mohammed V, Rabat, Morocco",
    date: "November 07, 2026",
    time: "8:00 PM - 10:30 PM",
  },
  {
    slug: "fred-again-india-tour-bengaluru",
    image: "/images/event2.jpeg",
    title: "Fred again.. Electro Live Showcase",
    location: "Bhartiya City, Bengaluru, KA",
    date: "November 14, 2026",
    time: "6:00 PM - 10:00 PM",
  },
  {
    slug: "sid-sriram-all-love-tour-coimbatore",
    image: "/images/event5.jpeg",
    title: "Sid Sriram: All Love Acoustic Session",
    location: "Codissia Amphitheatre, Coimbatore, TN",
    date: "November 21, 2026",
    time: "7:00 PM - 10:30 PM",
  },
  {
    slug: "guns-n-roses-live-bengaluru",
    image: "/images/event1.jpeg",
    title: "Guns N' Roses: Generation Live India",
    location: "M. Chinnaswamy Stadium, Bengaluru, KA",
    date: "December 02, 2026",
    time: "7:00 PM - 11:30 PM",
  },
  {
    slug: "santhosh-narayanan-live-madurai",
    image: "/images/event3.jpeg",
    title: "Santhosh Narayanan: Neeye Oli Experience",
    location: "Tamukkam Grounds, Madurai, TN",
    date: "December 19, 2026",
    time: "6:30 PM - 11:00 PM",
  },
  {
    slug: "sunburn-festival-chainsmokers-goa",
    image: "/images/event4.jpeg",
    title: "Sunburn Festival ft. The Chainsmokers",
    location: "Vagator Beach Arena, Goa, India",
    date: "December 28, 2026",
    time: "4:00 PM - 11:30 PM",
  },
  {
    slug: "ilayaraja-symphony-live-chennai",
    image: "/images/event2.jpeg",
    title: "Isaignani Ilaiyaraaja Live Symphony",
    location: "Island Grounds, Chennai, TN",
    date: "January 09, 2027",
    time: "6:00 PM - 10:30 PM",
  },
  {
    slug: "the-weeknd-after-hours-tokyo",
    image: "/images/event5.jpeg",
    title: "The Weeknd: Nightmare Stage Legacy Tour",
    location: "Tokyo Dome, Tokyo, Japan",
    date: "January 23, 2027",
    time: "7:00 PM - 10:30 PM",
  },
  {
    slug: "billie-eilish-hit-me-hard-sydney",
    image: "/images/event1.jpeg",
    title: "Billie Eilish: Hit Me Hard and Soft Tour",
    location: "Qudos Bank Arena, Sydney, Australia",
    date: "February 12, 2027",
    time: "7:30 PM - 10:45 PM",
  },
  {
    slug: "taylor-swift-eras-toronto-extended",
    image: "/images/event4.jpeg",
    title: "Taylor Swift: The Eras Tour Showcase",
    location: "Rogers Centre, Toronto, ON",
    date: "February 27, 2027",
    time: "6:00 PM - 11:00 PM",
  },
  {
    slug: "shreya-ghoshal-melodies-salem",
    image: "/images/event3.jpeg",
    title: "Shreya Ghoshal Symphony Nights",
    location: "Devee Theatre Grounds, Salem, TN",
    date: "March 13, 2027",
    time: "6:30 PM - 10:00 PM",
  },
  {
    slug: "dua-lipa-radical-optimism-mumbai",
    image: "/images/event2.jpeg",
    title: "Dua Lipa: Radical Optimism Tour India",
    location: "DY Patil Stadium, Mumbai, MH",
    date: "March 28, 2027",
    time: "7:00 PM - 10:30 PM",
  }
];